package hr.fer.zemris.java.hw15.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Cacheable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Class that models blog entry. It has properties:
 * 			id, list of comments, time it was created, time it was last modified, title, and text
 * All properties have getters and setters.
 * Property id is generated automatically by database.
 * 
 * Instances of this class are stored in database in table BLOG_ENTRIES.
 * 
 * @author Alex
 *
 */
@NamedQueries({
	@NamedQuery(name="BlogEntry.upit1",query="select b from BlogComment as b where b.blogEntry=:be and b.postedOn>:when")
})
@Entity
@Table(name="blog_entries")
@Cacheable(true)
public class BlogEntry {

	/**
	 * Autoincremented value generated by database, primary key.
	 */
	private Long id;
	
	/**
	 * List of comments added to this entry.
	 */
	private List<BlogComment> comments = new ArrayList<>();
	
	/**
	 * Time this entry was created.
	 */
	private Date createdAt;
	
	/**
	 * Time this entry was last modified.
	 */
	private Date lastModifiedAt;
	
	/**
	 * Title of blog entry.
	 */
	private String title;
	
	/**
	 * Text of blog entry.
	 */
	private String text;
	
	/**
	 * User that created this blog entry.
	 */
	private BlogUser creator;
	
	/**
	 * Getter for creator of blog entry.
	 * @return
	 * 				{@link BlogUser} that created this entry.
	 */
	@ManyToOne
	@JoinColumn(nullable=false)
	public BlogUser getCreator() {
		return creator;
	}

	/**
	 * Setter for creator.
	 * @param creator
	 * 				blog user who created this blog entry
	 */
	public void setCreator(BlogUser creator) {
		this.creator = creator;
	}

	/**
	 * Getter for id.
	 * @return
	 * 				id of blog entry
	 */
	@Id @GeneratedValue
	public Long getId() {
		return id;
	}
	
	/**
	 * Setter for id.
	 * @param id
	 * 				Long value of id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Getter for comments on this blog entry.
	 * @return
	 * 				list of {@link BlogComment} on this blog entry
	 */
	@OneToMany(mappedBy="blogEntry",fetch=FetchType.LAZY, cascade=CascadeType.PERSIST, orphanRemoval=true)
	@OrderBy("postedOn")
	public List<BlogComment> getComments() {
		return comments;
	}
	
	/**
	 * Setter for comments list.
	 * @param comments
	 * 				list of {@link BlogComment} added to this blog
	 */
	public void setComments(List<BlogComment> comments) {
		this.comments = comments;
	}

	/**
	 * Getter for time entry was created.
	 * @return
	 * 				time of creation
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(nullable=false)
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * Setter for time of creation.
	 * @param createdAt
	 * 				time entry was created
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * Getter for time entry was last modified.
	 * @return
	 * 				time entry was last modified
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(nullable=true)
	public Date getLastModifiedAt() {
		return lastModifiedAt;
	}

	/**
	 * Setter for time entry was last modified.
	 * @param lastModifiedAt
	 * 				time entry was last modified
	 */
	public void setLastModifiedAt(Date lastModifiedAt) {
		this.lastModifiedAt = lastModifiedAt;
	}

	/**
	 * Getter title of entry.
	 * @return
	 * 				title of blog entry
	 */
	@Column(length=200,nullable=false)
	public String getTitle() {
		return title;
	}

	/**
	 * Setter for title of blog entry.
	 * @param title
	 * 				title of blog entry
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Getter or text of blog entry.
	 * @return
	 * 				text of blog entry
	 */
	@Column(length=4096,nullable=false)
	public String getText() {
		return text;
	}

	/**
	 * Setter for text of blog entry.
	 * @param text
	 * 				text of blog entry
	 */
	public void setText(String text) {
		this.text = text;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BlogEntry other = (BlogEntry) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
}